default:
  tags:
    - ec2-amazon

stages:
  - security

security:checkov:
  stage: security
  image:
    name: bridgecrew/checkov:latest
    entrypoint: [""]
  rules:
    - changes:
        - "module/**/*.tf"
        - ".gitlab-ci.yml"
  script:
    - checkov -d "${CI_PROJECT_DIR}/module" --framework terraform --soft-fail-on MEDIUM --output cli --output junitxml --output-file-path .
  artifacts:
    reports:
      junit: results_junitxml.xml
    paths:
      - results_junitxml.xml
    expire_in: 1 week
    when: always
